import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "PSU GUIDE",
    description: "Generated by create next app",
    icons: {
        icon: ['/ico/favicon.ico?v=4'],
        apple: ['/ico/apple-touch-icon.png?v=4'],
        shortcut: ['/ico/apple-touch-icon.png?v=4'],
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="main-font">{children}</body>
        </html>
    );
}
