import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
import BottomNavbar from "../components/bottomNavbar"
import HeadNavbar from "../components/headNavbar"

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PSU GUIDE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="main-font">
        <HeadNavbar/>
        {children}
        <BottomNavbar/>
      </body>
    </html>
  );
}
